### ISSUE TITLE
Enhancement: LVZF compression

### ISSUE THREAD

**Issue by martinberlin** [amadeok/Epdiy-Eink-PC-monitor#3]
Hello Amadeo,

This is an idea that I used for another project. RLE can be great for monochrome only but still if the screen has lots of small sections LVZ will work much better. I implemented this only as a test for some price tags and the size was from 2.5 to 5 times smaller:

https://github.com/martinberlin/ATC_TLSR_Quirks/tree/main/Firmware/src
![lzf-compression](https://user-images.githubusercontent.com/2692928/152870157-16846b72-42bf-4342-a9d5-898f88724aaa.png)

Just an idea. If you want I can help you to implement it on the Espressif Firmware part.

**Comment by amadeok** [comment]
Hi
Our program already uses RLE compression( [](https://github.com/ChuOkupai/rle-compression/) ) to improve the wifi transfer, not sure which one would be more efficient in this case.
vroland (the guy who made the epdiy board) was working on a hardware solution that allowed data transfer between a epdiy board and the pc in USB high speed mode (up to 35 megabytes /s ) and he showed a video mirroring pc linux in 16 shades of grey at impressive framerates:
 https://www.youtube.com/watch?v=y5jk2ScpvmM
He told me that it wasnt ready just yet a few months ago, but i havent heard from him since. Maybe he's working on other things. The violet board you see there is a FT232H board which is easy and cheap to buy, but he green one below it is the custom one he designed and is the interface that allows the whole thing to work, and may need to be finished. Electronics is not my strong suit but if you are feeling adventurous you could ask him for the desing for that board and see what remains to sort out.

**Comment by martinberlin** [comment]
Hello Amadeo,
Sure I've seen that. I was just thinking that if you want to stream a Dithered image then LVZ will work better. Anyways I can try this myself and post some results here when I find the time. 

That with the FT232H board is a nice experiment, but the thing is that you need to send the high voltages (4 + VCOM) from an existing working board. So I guess real solution will be to make a PCB where you can add FT232H but drives the voltages so you don't have this mess of cables around. That seems something that can take some time to do.

**Comment by martinberlin** [comment]
Closing here, I think RLE is enough and works great alread.y. LZF would be something interesting just if you want to stream video or something alike
